#!/usr/bin/env bash
if [ -p /dev/stdin ]; then
	read IN
else
	IN=${1?Error: No input specified. 
            This is for ASCII to Hexadecimal Conversion
            
            Usage: a2h <ASCII>
            }
fi
python -c "print('$IN'.encode('hex'))"
