#!/usr/bin/env bash
if [ -p /dev/stdin ]; then
	read IN
else
	IN=${1?Error: No input specified. 
            
            Usage: hex2dec <hexadecimal>
            }
fi
python -c "print('$IN'.encode('hex'))"
