#!/usr/bin/env bash
if [ -p /dev/stdin ]; then
	read IN
else
	IN=${1?Error: No input specified. 
            This is for Hexadecimal 2 ASCII Conversion
            
            Usage: h2a <hexadecimal>
            }
fi
python -c "print('$IN'.decode('hex'))"
