#!/usr/bin/env bash
if [ -p /dev/stdin ]; then
	read IN
else
	IN=${1?Error: No input specified. 
            This is for Hexadecimal 2 Decimal Conversion
            
            Usage: h2d <hexadecimal>
            }
fi
python -c "print(int('$IN', base=16))"
