#!/usr/bin/env bash
FILE=${1?Error: No file specified. 
            
            Usage: typopen <filename>
            }
if test -f "$FILE"; then
    echo "opening $FILE in typora..."
    nohup open -a typora $FILE > /dev/null &
    disown
else
    echo "creating $FILE in typora..."
    touch $FILE
    nohup open -a typora $FILE > /dev/null &
    disown
fi
