#!/usr/bin/env bash
if [ -p /dev/stdin ]; then
	read IN1
	IN2=$1
else
	IN1=${1?Error: No input specified.
        This is for Hexadecimal XOR Calculations

		Usage: XOR <hexadecimal> <hexadecimal>
						}
	IN2=$2
fi
# echo $IN1 $OP $IN2
python -c "print(hex(int('$IN1', base=16) ^ int('$IN2', base=16)).split('x')[-1])"
